### PR TITLE
Remove @EnableAsync and @EnableScheduling to avoid conflicts.

### LINKED ISSUE #780: Application fails to start in Kubernetes when using target-class based (CGLIB) proxies (e.g., with EnableAsync)
**Describe the bug**
Hi there,

I'm currently using Spring Cloud Kubernetes, but run into an application startup issue after attempting to use an asynchronous method.
A sample Maven project to help reproduce the issue can be found in this repo : [rm3l/sck-issue-with-target-class-proxies](https://github.com/rm3l/sck-issue-with-target-class-proxies)

The error message (stack trace below) explicitly tells me to `Either pull the async method up to an interface or switch to CGLIB proxies by enforcing proxy-target-class mode`.
I don't understand why, since the use of CGLIB proxies is already being enforced application-wide (via the .`spring.aop.proxy-target-class` [Spring Boot property](https://docs.spring.io/spring-boot/docs/current/reference/html/appendix-application-properties.html#spring.aop.proxy-target-class) and the `proxyTargetClass=true` attribute of the `EnableAsync` annotation) 

I am not sure though if this is an issue related to Spring Cloud Kubernetes itself, or if it relates to Spring Boot instead.
Maybe I missed something, but the application starts and works like a charm when started outside of Kubernetes or when I explicitly set `spring.cloud.kubernetes.enabled=false`, which makes me suspect an issue with Spring Cloud Kubernetes.

Is there anything in Spring Cloud Kubernetes forcing the use of standard Java interface-based proxies, irrespective of how the application is configured ?

Below is an excerpt from the error log:
```
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2021-05-02 20:38:53.179 ERROR 1 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanInitializationException: Failed to process @EventListener annotation on bean with name 'testServiceImpl'; nested exception is java.lang.IllegalStateException: Need to invoke method 'handleEvent' declared on target class 'TestServiceImpl', but not found in any interface(s) of the exposed proxy type. Either pull the method up to an interface or switch to CGLIB proxies by enforcing proxy-target-class mode in your configuration.
	at org.springframework.context.event.EventListenerMethodProcessor.afterSingletonsInstantiated(EventListenerMethodProcessor.java:157) ~[spring-context-5.3.6.jar:5.3.6]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:963) ~[spring-beans-5.3.6.jar:5.3.6]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918) ~[spring-context-5.3.6.jar:5.3.6]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583) ~[spring-context-5.3.6.jar:5.3.6]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:144) ~[spring-boot-2.4.5.jar:2.4.5]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:782) ~[spring-boot-2.4.5.jar:2.4.5]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:774) ~[spring-boot-2.4.5.jar:2.4.5]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:439) ~[spring-boot-2.4.5.jar:2.4.5]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:339) ~[spring-boot-2.4.5.jar:2.4.5]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1340) ~[spring-boot-2.4.5.jar:2.4.5]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1329) ~[spring-boot-2.4.5.jar:2.4.5]
	at org.rm3l.springcloudkubernetesissuewithtargetclassproxies.SpringCloudKubernetesIssueWithTargetClassProxiesApplication.main(SpringCloudKubernetesIssueWithTargetClassProxiesApplication.java:12) ~[classes/:na]
Caused by: java.lang.IllegalStateException: Need to invoke method 'handleEvent' declared on target class 'TestServiceImpl', but not found in any interface(s) of the exposed proxy type. Either pull the method up to an interface or switch to CGLIB proxies by enforcing proxy-target-class mode in your configuration.
	at org.springframework.core.MethodIntrospector.selectInvocableMethod(MethodIntrospector.java:132) ~[spring-core-5.3.6.jar:5.3.6]
	at org.springframework.aop.support.AopUtils.selectInvocableMethod(AopUtils.java:135) ~[spring-aop-5.3.6.jar:5.3.6]
	at org.springframework.context.event.EventListenerMethodProcessor.processBean(EventListenerMethodProcessor.java:198) ~[spring-context-5.3.6.jar:5.3.6]
	at org.springframework.context.event.EventListenerMethodProcessor.afterSingletonsInstantiated(EventListenerMethodProcessor.java:154) ~[spring-context-5.3.6.jar:5.3.6]
	... 11 common frames omitted
```

For reference, I am using the following versions:
- Spring Boot : 2.4.5
- Spring Cloud Kubernetes : 2.0.2

**Sample**
I've created this sample Maven project to help reproduce the issue: https://github.com/rm3l/sck-issue-with-target-class-proxies

This repo contains a simple Helm Chart for deploying to Kubernetes. It also contains a GitHub Workflow that tests this Chart. This job currently does not pass due to this issue.
Please do let me know if there is anything missing or if I can help further investigate.
Thanks.

### PR DESCRIPTION
**Pull request by ryanjbaxter**
Fixes #780

### CODE REVIEW

**Comment by ryanjbaxter** [comment]
Integration tests using polling watcher passes, and I verified this locally.

File: spring-cloud-kubernetes-config/src/main/java/org/springframework/cloud/kubernetes/config/reload/ConfigReloadAutoConfiguration.java [hunk 1]
```diff
@@ -102,6 +102,12 @@ public ConfigurationChangeDetector propertyChangeWatcher(
 					"Unsupported configuration reload mode: " + properties.getMode());
 		}
 
+		@Bean
+		@ConditionalOnMissingBean
+		public TaskScheduler taskScheduler() {
```
Comment (spencergibb) [inline spring-cloud-kubernetes-config/src/main/java/org/springframework/cloud/kubernetes/config/reload/ConfigReloadAutoConfiguration.java:107]: Creating a bean of type `TaskScheduler` was brought up in s-c-consul. https://github.com/spring-cloud/spring-cloud-consul/issues/723
We should come up with some consistency

Comment (ryanjbaxter) [reply spring-cloud-kubernetes-config/src/main/java/org/springframework/cloud/kubernetes/config/reload/ConfigReloadAutoConfiguration.java:107]: I guess my thought was to create a bean that the app could then customize if they wanted to.  I think the approach `spring-vault` takes makes it so there is no collision between `TaskScheduler` beans an app might create and the one used by `spring-vault`.  I could see both approaches being valid.  Maybe a nice middle ground is we use a `TaskSchedulerWrapper` but make it `@ConditionalOnMissingBean` so that if they do want to customize the behavior of that particular `TaskScheduler` they could but at the same time if the app creates its own `TaskScheduler` we avoid any kind of unintended consequences?

Comment (spencergibb) [reply spring-cloud-kubernetes-config/src/main/java/org/springframework/cloud/kubernetes/config/reload/ConfigReloadAutoConfiguration.java:107]: That sounds like a good idea. I'll do this in that consul issue as well.
